### ISSUE TITLE
Plots.compute_metrics() does not work with bayesian_samples < 2

### ISSUE THREAD

**Issue by javivilladamigo** [heidelberg-hepml/GenerativeUnfolding#4]
Error message below. Using n_unfoldings = 2 and bayesian_samples = 1 gives an error when calling the GetEMD function. Probably has to do with the dimensions access to the arrays.

Using device CPU
------- Loading data -------
    Process: ZJetsGenerative, loader ours
    Train events: 976729
    Val events: 81394
    Test events: 569760
    Hard dimension: 6
    Reco dimension: 6
------- Building model -------
    Using method: GenerativeUnfolding
    Model class: CFM
        Trajectory: Linear with t_noise 0 and minimum_noise 0
        c_embedding: None
        x_embedding: None
        t_embedding: None
        Network: Subnet with 26226 parameters
        Bayesian set to True, Bayesian layers:  4
        t distribution: uniform
        latent space: gaussian
        ODE solver: dopri5, atol 1e-05, rtol 1e-05, t [0.0, 1.0]
    Total trainable parameters: 26226
    Using EMA with start at 0.8
------- Running evaluation -------
Checkpoint: final,  Data: test
    Generating single samples
    Finished bayesian sample 0 in 67.59896993637085
Samples shape: torch.Size([1, 2, 569760, 6])
    Generation completed after 0:01:08
    Generating distributions
    Computing observables
    Computing metrics
Traceback (most recent call last):
  File "/usr/local/bin/src", line 33, in <module>
    sys.exit(load_entry_point('GenerativeUnfolding', 'console_scripts', 'src')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamarino/Documents/Heidelberg/Work/Unfolding/GenerativeUnfolding/src/__main__.py", line 11, in main
    args.func(args)
  File "/Users/jamarino/Documents/Heidelberg/Work/Unfolding/GenerativeUnfolding/src/train/main.py", line 49, in run_plots
    eval_model(doc, params, model, process)
  File "/Users/jamarino/Documents/Heidelberg/Work/Unfolding/GenerativeUnfolding/src/train/main.py", line 331, in eval_model
    evaluation(doc, params, model, process)
  File "/Users/jamarino/Documents/Heidelberg/Work/Unfolding/GenerativeUnfolding/src/train/main.py", line 134, in evaluation_generative
    plots = Plots(
            ^^^^^^
  File "/Users/jamarino/Documents/Heidelberg/Work/Unfolding/GenerativeUnfolding/src/train/plots.py", line 103, in __init__
    self.compute_metrics()
  File "/Users/jamarino/Documents/Heidelberg/Work/Unfolding/GenerativeUnfolding/src/train/plots.py", line 740, in compute_metrics
    emd_full_full, emd_full_full_std = GetEMD(x_true, x_gen[1:].flatten(), nboot=3)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamarino/Documents/Heidelberg/Work/Unfolding/GenerativeUnfolding/src/train/utils.py", line 18, in GetEMD
    array_boot = array[arr_idx]
                 ~~~~~^^^^^^^^^
IndexError: arrays used as indices must be of integer (or boolean) type

**Comment by javivilladamigo** [comment]
Does not have anything to do with n_unfoldings. Independently of its value GetEMD() will throw an error if bayesian_samples = 1.
